language:
  - python
  - node_js

python:
  - "2.7"
  - "3.3"

install:

  # Python stuff
  - pip install -r dev-requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors

  # Install grunt-cli and grunt
  - npm install -g grunt-cli
  - npm install

script:
  - grunt lint --force
  - grunt test --virtualenv $VIRTUAL_ENV

after_success:
  - coveralls
