"""Use native JSON for entry.content on postgres

Revision ID: 2213b8196921
Revises: 2b7f5e38dd73
Create Date: 2013-12-15 13:48:25.988000

"""

# revision identifiers, used by Alembic.
revision = '2213b8196921'
down_revision = '2b7f5e38dd73'

from marvin.types import JSONType

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'content',
               existing_type=JSONType(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'content',
               existing_type=JSONType(),
               nullable=False)
    ### end Alembic commands ###
