"""Add cover_img

Revision ID: 2c76677d803f
Revises: 6fae75bb79c
Create Date: 2013-11-15 01:35:07.692000

"""

# revision identifiers, used by Alembic.
revision = '2c76677d803f'
down_revision = '6fae75bb79c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('cover_img', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'cover_img')
    ### end Alembic commands ###
