"""Add movie.duration_in_s

Revision ID: 349d38252295
Revises: 2b7f5e38dd73
Create Date: 2014-01-09 15:31:24.597000

"""

# revision identifiers, used by Alembic.
revision = '349d38252295'
down_revision = '2b7f5e38dd73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('duration_in_s', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'duration_in_s')
    ### end Alembic commands ###
