"""Add title to entries. Make entry_point_in_ms nullable=False.

Revision ID: 6fae75bb79c
Revises: 2fc2a1f6946d
Create Date: 2013-11-11 18:51:19.719000

"""

# revision identifiers, used by Alembic.
revision = '6fae75bb79c'
down_revision = '2fc2a1f6946d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('title', sa.String(length=30), nullable=False))
    op.alter_column('entry', 'entry_point_in_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'entry_point_in_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('entry', 'title')
    ### end Alembic commands ###
