"""Add stream.public field

Revision ID: 872b6c03db1
Revises: 2c240cb3edd1
Create Date: 2014-02-11 18:42:28.748000

"""

# revision identifiers, used by Alembic.
revision = '872b6c03db1'
down_revision = '2c240cb3edd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('public', sa.Boolean(), nullable=False, server_default='false'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'public')
    ### end Alembic commands ###
